levelfive_second_project/levelfive_second_app/urls.py
from django.conf.urls import url
from levelfive_second_app import views

app_name = 'levelfive_second_app'

urlpatterns = [
    url(r'^$',views.index,name = 'index'),
    url(r'^register/$',views.register,name = 'register'),
    url(r'^login/$',views.userlogin,name = 'userlogin'),
]

levelfive_second_project/levelfive_second_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from levelfive_second_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name = 'index'),
    path('levelfive_second_app/',include('levelfive_second_app.urls'))
]

levelfive_second_project/levelfive_second_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserprofileDetail(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to = 'profile_pics',blank = True)
    site_protifilo = models.URLField(blank = True)

    def __str__(self):
        return self.user.username

levelfive_second_project/levelfive_second_app/forms.py
from django import forms
from levelfive_second_app.models import UserprofileDetail
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserprofileDetail
        fields = ('profile_picture','site_protifilo')

levelfive_second_project/levelfive_second_app/views.py
from django.shortcuts import render
from levelfive_second_app.forms import UserForm,UserProfileForm
from django.contrib.auth.models import User

#This all import for login and logout............................
from django.contrib.auth import authenticate,login,logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
#................................................................
# Create your views here.
def index(request):
    return render(request,'levelfive_second_app/index.html')

def register(request):
    registered = False


    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        user_profile_form = UserProfileForm(data = request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile_form.save(commit = False)
            profile.user = user  #creating that OneToOneField relation

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True



        else:
            print(user.errors,profile.errors)

    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()

    return render(request,'levelfive_second_app/register.html',context = {'user_form':user_form , 'user_profile_form':user_profile_form,'registered':registered})

def userlogin(request):

    if request.method == "POST":
        username = username.POST.get('username')
        password = password.POST.get('password')

        user = authenticate(username = 'username' , password = 'password')

        if user:
            if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse(index))

            else:
                return HttpResponse('Account not activate')


        else:
            print('Someone tried to login with username:{} and password:{}'.format(username,password))
    else:
        return render(request,'levelfive_second_app/login_logout.html',{})

@login_required
def userlogout(request):
    logout(request)
    return HttpResponseRedirect(reverse(index))

levelfive_second_project/templates/levelfive_second_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  </head>
  <body>
    <nav class = "navbar navbar-expand-lg navbar-light bg-light">
      <a class = "navbar-brand" href="{% url 'index' %}">Home</a>

      <div class="collapse navbar-collapse">
        <ul class = "navbar-nav">
          <li class = "nav-item">
            <a class = 'nav-link' href="{% url 'levelfive_second_app:register' %}">Register</a>
          </li>

          <li class = "nav-item active">
            <a class = "nav-link" href="#">Admin</a>
          </li>

          {% if user.is_authenticated %}
          <li class = "nav-item active">
            <a  class = 'nav-link' href="{% url 'logout' %}">Login</a>
          </li>
          {% else %}
          <li class = "nav-item active">
            <a  class = 'nav-link' href="{% url 'levelfive_second_app:userlogin' %}">Login</a>
          </li>
          
        </div>
    </nav>

    {% block body_block %}

    {% endblock %}
  </body>
</html>

levelfive_second_project/templates/levelfive_second_app/index.html
<!DOCTYPE html>
{% extends 'levelfive_second_app/base.html' %}
  {% block body_block %}
    <div class="jumbotron">
      <h2>Welcome to First Page!</h2>
    </div>
  {% endblock %}

levelfive_second_project/templates/levelfive_second_app/login_logout.html
<!DOCTYPE html>
{% extends 'levelfive_second_app/base.html' %}
  {% block body_block %}
    <form enctype="multipart/form-data" action="index.html" method="POST">
      <label for="username">Username</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password</label>
      <input type="password" name="password" >

      <input type="submit"  value="Login">
    </form>
  {% endblock %}

levelfive_second_project/templates/levelfive_second_app/register.html
<!DOCTYPE html>
{% extends 'levelfive_second_app/base.html' %}
  {% block body_block %}
    {% if registered %}
      <h1>Thank you for registeration</h1>
    {% else %}
      <h1>Please register first</h1>

    <form enctype="multipart/form-data"  method="POST">
      {% csrf_token %}
      <!--Calling views context at last which we have written  render(request,'levelfive_second_app/register.html',context = {'user_form':user_form , 'user_profile_form':user_profile_form}) -->
      <!-- which have written inside two quotes '' that is called here -->
      {{user_form.as_p}}
      {{user_profile_form.as_p}}


      <input type="submit" name="" value="Submit">
    </form>
    {% endif %}
  {% endblock %}